# Default values for your projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Add annotations to the pods
podAnnotations: {}
# Add labels to the pods
podsLabels: {}
podManagementPolicy: "Parallel"
updateStrategy: RollingUpdate
nodeSelector: {}
tolerations: []
# By default this will make sure two pods don't end up on the same node
# Changing this to a region would allow you to spread pods across regions
antiAffinityTopologyKey: "kubernetes.io/hostname"
# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "hard"
# This is the node affinity settings as defined in
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: {}
nameOverride: temp
# Add labels to the deployment
deploymentLabels: {}
simbeSecrets:
  name: simulator-be
image:
  repository: 041640568050.dkr.ecr.eu-central-1.amazonaws.com/peaqnetwork/peaq-network-ev-charging-sim-be
  tag: 0.1.34
  pullPolicy: IfNotPresent
redis:
  name: redis
  image: redis
  tag: latest
  internalPort: 6379
simp2p:
  name: simp2p
  image: 041640568050.dkr.ecr.eu-central-1.amazonaws.com/peaqnetwork/peaq-network-ev-charging-sim-be-p2p
  tag: latest
# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []
  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true
# define environment variables here as a map of key: value
env:
# enable this flag to use knative serve to deploy the app
knativeDeploy: false
# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80
  # Add labels to the HPA
  labels: {}
# Canary deployments
# If enabled, Istio and Flagger need to be installed in the cluster
canary:
  enabled: false
  progressDeadlineSeconds: 60
  analysis:
    interval: "1m"
    threshold: 5
    maxWeight: 60
    stepWeight: 20
    # WARNING: Canary deployments will fail and rollback if there is no traffic that will generate the below specified metrics.
    metrics:
      latency:
        threshold: 500
        interval: "1m"
  # The host is using Istio Gateway or the underlying ingress mechanism
  # This value is defaulted from the environments jx-requirements.yml ingress configuration
  host: ""
  # Add labels to the canary
  labels: {}
  # Add labels to the canary gateway
  gatewayLabels: {}
service_p2p:
  name: peaq-network-ev-charging-sim-be-p2p
  type: LoadBalancer
  externalPort: 10333
  internalPort: 10333
  annotations: {}
  # Add labels to the service
  labels: {}
service:
  name: peaq-network-ev-charging-sim-be
  type: ClusterIP
  externalPort: 80
  internalPort: 25566
  annotations: {}
  # Add labels to the service
  labels: {}
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: ""
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: ""
# custom ingress annotations on this service
ingress:
  annotations: {}
  # defaults to nginx if no other ingress class annotation specified
  classAnnotation: ""
  # Add labels to the ingress
  labels: {}
  # ingress path type
  pathType: ImplementationSpecific
serviceAccount:
  enabled: true
  name: ""
  annotations: {}
  #    iam.gke.io/gcp-service-account: my-sa-in-gke
  # Add labels to the SA
  labels: {}
#    my-custom-label: value

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    # shared ingress annotations on all services
    annotations: {}
    #  kubernetes.io/ingress.class: nginx

    apiVersion: "networking.k8s.io/v1"
    # the domain for hosts
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
